[package]
name = "raytracing"
version = "0.1.0"
authors = ["CubeArrow <1984flaker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
threadpool = "1.8.1"